function handleSlider=createSlider(h,edit_box,pSlider,sliderCallbackHandle)
h;
if strcmp(edit_box.Enable, 'on')
    enbl='on';
else
    enbl='off';
end
textValue = str2num(get(edit_box,'String'));%get the default parameter value
handleSlider = uicontrol('Style', 'slider',...
    'Units', 'normalized',...
    'position',pSlider,...
    'Min',0,'Max',10,'Value',textValue,...
    'Enable',enbl,...
    'callback',sliderCallbackHandle);
%'position', [leftMargin, bottomInstruction+verticalSpace+2, editBoxWidth+horizontalSpace+textBoxWidth, 15],...
end