classdef NIPState < uint16
    enumeration
        % Do not use 0 becuase numeric values are used as array indices
        Ready (1), ...
        ReadImages (2), ...
        
    
        SegmentedNucleusImageOnce (3), ...
        SegmentedNucleusImageTwice (4), ...
        OpenedNucleusMask (5), ...
        IdentifiedNucleusClusters (6), ...
        CalculatedNominalMeanNucleusArea (7), ...
        CalculatedMinNucleusArea (8), ...
    
    
        SegmentedCells (9), ...
        SeparatedBodiesFromNeurites (10), ...
        ResegmentedNeurites (11), ...
        ClosedNeuriteMask (12), ...
        
        
        
        SkeletonizedNeurites (13), ,,,
        CreatedGraph (14), ComputedPaths (15), ...
        Done (16)
    end
  
end
